backdrop-contrib/ckeditor5

ckeditor5.admin.inc, ckeditor5.module, js/ckeditor5.admin.js
Fixes https://github.com/quicksketch/ckeditor5/issues/7
=> CKEditor5 #7: Support for enabling headings.

ckeditor5.module
Fixes https://github.com/quicksketch/ckeditor5/issues/19
=> CKEditor5 #19: Fix loading plugins that use an enabled callback.

ckeditor5.module, js/plugins/backdrop-link/backdrop-link.js
Fixes https://github.com/quicksketch/ckeditor5/issues/21
=> CKEditor5 #21: Fix adding dependencies when enabled via a toolbar button.

ckeditor5.module
=> CKEditor5 #12: Fix icon for Code Block button.

ckeditor5.admin.inc
=> Issue #29: PHP warnings when adding a CKE5-enabled filter in PHP 8.1

README.md
=> Issue #41: Co-maintain

.gitattributes, .github/misc/Github.php, .github/misc/default.conf, .github/misc/settings.local.php, .github/workflows/code-checks.yml, .github/workflows/functional-tests.yml, LICENSE.txt, ckeditor5.info, ckeditor5.module
=> Issue #44: Fix some obvious tasks

.github/workflows/code-checks.yml
=> Issue #44: Fix phpcs test run path

ckeditor5.admin.inc, ckeditor5.api.php, ckeditor5.install, ckeditor5.module, ckeditor5.pages.inc, tests/ckeditor5.test, tests/ckeditor5_rtl.test
=> Issue #47: automated test and phpcs errors

ckeditor5.module, js/ckeditor5.js
=> Issue #28: Generic HTML support based on filter settings

ckeditor5.install
=> Issue #50: Clarify status report message about unused editor

ckeditor5.module, js/plugins/backdrop-image/backdrop-image.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/1 (well not quite, but it's a start!)
=> Issue #1: Initial Backdrop image library integration.

ckeditor5.api.php, ckeditor5.module, css/ckeditor5.css, js/plugins/backdrop-image/backdrop-image.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/53
=> Issue #53: Integrate image alignment support.

js/plugins/backdrop-image/backdrop-image.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/63
=> Issue #63: Handle resized images in CKEditor v40.

tests/ckeditor5.test, tests/ckeditor5.tests.info, tests/ckeditor5_rtl.test
=> Issue #61: Actually run tests with ckeditor5 module

ckeditor5.module, css/ckeditor5.css, js/plugins/backdrop-image/backdrop-image.js, js/plugins/backdrop-link/backdrop-link.js
Add support for linking images. Includes support for extra attributes like `title`, `id`, `class`, etc.
=> Issue #54: Add image link handling.

ckeditor5.module, js/ckeditor5.compat.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/43.
=> Issue #43: Provide another temporary work-around for CKEditor 4.

js/ckeditor5.compat.js
=> Issue #78: Fix console warning when v4 not set in formats

ckeditor5.module, js/plugins/backdrop-image/backdrop-image.js, js/plugins/backdrop-link/backdrop-link.js
=> Issue #17: Add new separate backdropLink button.

ckeditor5.module, js/ckeditor5.formatter.js, js/ckeditor5.js
=> Issue #37: Provide a warning if content will be modified by attaching editor.

ckeditor5.admin.inc
=> Issue #85: Fix admin form item for backdropLink plugin settings

ckeditor5.theme.inc, css/ckeditor5.admin.css, js/ckeditor5.admin.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/31
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/35
=> Issue #31: Add keyboard navigation to button configuration. Admin CSS cleanup.

ckeditor5.module
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/84
=> Issue #84: Add CKEditor 5 version to telemetry.

ckeditor5.module, js/ckeditor5.admin.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/14.
=> Issue #14: Fix hiding disabled button settings. Update ckeditor5.admin.js variable declaration.

js/plugins/backdrop-image/backdrop-image.js
Fixes #95 - no it doesn't, but fixes the easy part.
=> Issue #95: Do not reject resized images

js/plugins/backdrop-image/backdrop-image.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/66.
=> Issue #66: Fix handling of resized images with CKEditor v40.1.0.

js/ckeditor5.js
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/22
=> Issue #22: Intermittently save value to prevent data loss.

ckeditor5.admin.inc
=> Issue #105: Vertical tabs add some cruft to settings file

ckeditor5.module
Fixes #109 - alternative approach
=> Issue #109: Tweak ListPropertiesStyleConfig to only allow reversed and startIndex by default

ckeditor5.admin.inc, ckeditor5.api.php, ckeditor5.install, ckeditor5.module, ckeditor5.theme.inc, js/ckeditor5.admin.js, tests/ckeditor5.test
=> Issue #113: Rename config key to toolbar.

.github/workflows/functional-tests.yml, ckeditor5.install, ckeditor5.upgrade.inc, tests/ckeditor5_upgrade.test, tests/ckeditor5_upgrade_test/ckeditor5_upgrade_test.module
Fixes #113. Follow-up to properly save config.
=> Issue #113: Fix update hook to save config changes.

tests/ckeditor5_rtl.test
Fixes https://github.com/backdrop-contrib/ckeditor5/issues/122.
=> Issue #122: Fix RTL test to check for CKEditor 5 icons.
